clone:
  path: github.com/drone-plugins
  recursive: true

build:
  image: armhfbuild/golang:1.5
  environment:
    - GO15VENDOREXPERIMENT=1
    - GOOS=linux
    - GOARCH=arm
    - CGO_ENABLED=0
  commands:
    - git clone --single-branch https://github.com/drone-plugins/drone-irc/
    - cd drone-irc/
    - sed -i 's/FROM alpine/FROM armhfbuild\/alpine/' Dockerfile
    - go get
    - go build
    - go test

publish:
  docker:
    username: $$DOCKER_USER
    password: $$DOCKER_PASSWORD
    email: $$DOCKER_EMAIL
    repo: armhfplugins/drone-irc
    when:
      repo: armhf-drone-plugins/drone-irc
      branch: master

notify:
  slack:
    webhook_url: $$SLACK_WEBHOOK_URL
    channel: armhf

plugin:
  name: IRC
  desc: Send build status notifications via IRC
  type: notify
  image: armhfplugins/drone-irc
  labels:
    - chat
    - messaging
    - irc
